provider "newrelic" {
  
}

locals {
  csv_data = <<-CSV
    system
    usa.gov
    10x.gsa.gov
    18f.domains.api.data.gov
    18f.gov
    18f.gsa.gov
    18franklin.18f.gov
    aapi.data.gov
    accessibility.18f.gov
    accessibility.digital.gov
    acqstack-journeymap.18f.gov
    acquisitions.18f.gov/
    admin-catalog.data.gov
    admin.digitalgov.gov
    ads.18f.gov
    ag.data.gov
    agile-bpa.18f.gov
    agile-labor-categories.18f.gov
    agile.18f.gov
    agriculture.data.gov
    airnowtome.app.cloud.gov
    alpha.data.gov
    analytics-staging.app.cloud.gov
    analytics.fr.cloud.gov
    analytics.usa.gov
    answers.usa.gov
    api-all-the-x.18f.gov
    api-program.18f.gov
    api-usability-testing.18f.gov
    api.18f.gov
    api.code.gov
    api.data.gov
    api.usa.gov
    app-empathic-otter.app.cloud.gov
    app.brody.identitysandbox.gov
    app.cloud.gov
    app.markryan.identitysandbox.gov
    apply.pif.gov
    apps.gobiernousa.gov
    apps.gov
    apps.usa.gov
    asis.search.gov
    asis.search.usa.gov
    atf-eregs-demo.app.cloud.gov
    atf-eregs.18f.gov
    atf-eregs.app.cloud.gov
    atul-docker-presentation.18f.gov
    autoapi.18f.gov
    autodiscover.apps.gov
    automated-testing-playbook.18f.gov
    banks-q.app.cloud.gov
    before-you-ship.18f.gov
    beta.vote.gov
    blog.gobiernousa.gov
    blog.usa.gov
    blogging-guide.18f.gov
    boise.18f.gov
    brand.18f.gov
    brody.identitysandbox.gov
    buscador.usa.gov
    business.usa.gov
    businessusa.data.gov
    businessusa.gov
    c2.18f.gov
    calc-dev.app.cloud.gov
    calc.gsa.gov
    cap.18f.gov
    cap.18f.gov/
    catalog-bsp.data.gov
    catalog-next.data.gov
    catalog.data.gov
    challenge.gov
    challenges.gov
    charlie.18f.gov
    chat.18f.gov
    ci.identitysandbox.gov
    cities.data.gov
    citizenscience.gov
    cld.epa.gov
    climate-data-user-study.18f.gov
    climate.data.gov
    cloud.gov
    cm-jira.usa.gov
    code.gov
    coe.gsa.gov
    college-scorecard.app.cloud.gov
    collegescorecard.ed.gov
    compliance-viewer.18f.gov
    components.designsystem.digital.gov
    components.standards.usa.gov
    computersforlearning.gov
    conectate.gobiernousa.gov
    connect.digitalgov.gov
    connect.gov
    connect.usa.gov
    consumer.data.gov
    consumeraction.gov
    consumercomplaintletter.usa.gov
    content-guide.18f.gov
    continua11y.18f.gov
    contracting-cookbook.18f.gov
    counties.data.gov
    crime-data-explorer.fr.cloud.gov
    crissupb.identitysandbox.gov
    dap.digitalgov.gov/Universal-Federated-Analytics-Min.js
    data.gov
    demo.10x.gsa.gov
    demo.accessibility.digital.gov
    demo.digital.gov
    demo.digitalgov.gov
    demo.fedramp.gov
    demo.innovation.gov
    demo.plainlanguage.gov
    demo.pra.digital.gov
    demo.touchpoints.digital.gov
    design-principles-guide.18f.gov
    designsystem.digital.gov
    dev.identitysandbox.gov
    developer.data.gov
    developers.code.gov
    developers.login.gov
    digital-acquisition-playbook.18f.gov
    digital.gov
    digitalaccelerator.18f.gov
    digitalgov.gov
    disaster.data.gov
    disasters.data.gov
    discovery.gsa.gov
    docs.cloud.gov
    dolores-app.18f.gov
    dolores-staging.18f.gov
    ecosystems.data.gov
    ed.data.gov
    education.data.gov
    emerging.digital.gov
    eng-hiring.18f.gov
    engineering.18f.gov
    epa-notice.usa.gov
    ethics.data.gov
    everykidinapark.gov
    federalist-docs.18f.gov
    federalist.18f.gov
    federalistapp-staging.18f.gov
    federalistapp.18f.gov
    federation-staging.data.gov
    federation.data.gov
    fedramp.gov
    fedramp.sitesusa.app.cloud.gov
    fedspendingtransparency.18f.gov
    feedback-staging.usa.gov
    feedback.usa.gov
    feedthefuture.gov
    fellows-in-innovation.pif.gov
    finance.data.gov
    find.digitalgov.gov
    find.search.gov
    findtreatment.gov
    firstgov.gov
    food.data.gov
    foodsecurity.data.gov
    forms.gov
    frontend.18f.gov
    geospatial.data.gov
    globaldevelopment.data.gov
    go.usa.gov
    gobierno.usa.gov
    gobiernousa.gov
    govconnect.18f.gov
    grouplet-playbook.18f.gov
    guides-template.18f.gov
    guides.18f.gov
    handbook.18f.gov
    handbook.tts.gsa.gov
    health.data.gov
    highlights.data.gov
    devicepki.idmanagement.gov
    hackerone.com/tts
    https.app.cloud.gov
    https.cio.gov
    humanrights.data.gov
    iaa-forms.18f.gov
    identity-dev-docs.18f.gov
    idmanagement.gov
    idp.staging.login.gov
    info.gov
    innovation-toolkit-prototype.18f.gov
    innovation.gov
    int.identitysandbox.gov
    inventory.data.gov
    jjg.identitysandbox.gov
    jobkit.data.gov
    jobs.18f.gov
    join.18f.gov
    join.tts.gsa.gov
    kids.gov
    kids.usa.gov
    labs.data.gov
    labs.usa.gov
    law.data.gov
    lean-product-design.18f.gov
    login.fr.cloud.gov
    login.gov
    lookforwatersense-prod.app.cloud.gov
    m.gobiernousa.gov
    m.usa.gov
    make.data.gov
    manufacturing.data.gov
    markdown-helper.18f.gov
    marketplace.fedramp.gov
    markryan.identitysandbox.gov
    methods.18f.gov
    micropurchase.18f.gov
    modularcontracting.18f.gov
    my.usa.gov
    next.data.gov
    notice.data.gov
    notice.usa.gov
    notifications.usa.gov
    nutrition.data.gov
    ocean.data.gov
    open-forest-dev.app.cloud.gov
    open-forest-staging.app.cloud.gov
    open-source-guide.18f.gov
    open-source-program.18f.gov
    open-staging.usa.gov
    open.foia.gov
    open.usa.gov
    openopps.digitalgov.gov
    pages.18f.gov
    paid-leave-prototype.18f.gov
    participation.usa.gov
    partnership-playbook.18f.gov
    paygap.pif.gov
    performance-gov-research.18f.gov
    performance.gov
    pif.gov
    piv.idmanagement.gov
    plain-language-tutorial.18f.gov
    plainlanguage.gov
    pra.digital.gov
    presidentialinnovationfellows.gov
    private-eye.18f.gov
    product-guide.18f.gov
    promotions.usa.gov
    proposal.pif.gov
    public-sans.digital.gov
    publications.usa.gov
    pulse.cio.gov
    reference.data.gov
    registry.usa.gov
    requests.18f.gov
    research.data.gov
    resources-staging.data.gov
    resources.data.gov
    respuestas.gobiernousa.gov
    rural.data.gov
    safety.data.gov
    sbst.gov
    science.data.gov
    sdg-staging.data.gov
    sdg.data.gov
    search.data.gov
    search.digitalgov.gov
    search.gov
    search.usa.gov
    secure.login.gov
    semantic.data.gov
    services.data.gov
    site-scanning.app.cloud.gov
    skills.data.gov
    slides.18f.gov
    smallbusiness.data.gov
    smartdisclosure.data.gov
    staging.code.gov
    staging.login.gov
    staging.performance.gov
    staging.vote.gov
    standards.usa.gov
    states.data.gov
    strategy.data.gov
    summit.digitalgov.gov
    tailored.fedramp.gov
    testing-cookbook.18f.gov
    tock.18f.gov
    tophealth.pif.gov
    touchpoints.digital.gov
    us.gov
    usagov.gov
    usdigitalregistry.digitalgov.gov
    v1.designsystem.digital.gov
    v2.designsystem.digital.gov
    vocab.data.gov
    vote.gov
    vote.usa.gov
    weather.data.gov
    workflow.digital.gov
    wp-bsp.data.gov
    writing-lab-guide.18f.gov
  CSV

  endpoints = csvdecode(local.csv_data)
}

resource "newrelic_synthetics_monitor" "forloop" {
  for_each = { for inst in local.endpoints : inst.system => inst }

  bypass_head_request       = "false"
  frequency                 = "10"
  locations                 = ["AWS_US_EAST_1", "AWS_US_WEST_1", "AWS_US_WEST_2"]
  name                      = each.value.system
  sla_threshold             = "10"
  status                    = "ENABLED"
  treat_redirect_as_failure = "false"
  type                      = "SIMPLE"
  uri                       = "https://${each.value.system}"
  verify_ssl                = "false"
}